
SUPABASE_URL='https://ceypqwcxflnqzcggyqor.supabase.co'
SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNleXBxd2N4ZmxucXpjZ2d5cW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NjcxMjUsImV4cCI6MjA3OTI0MzEyNX0.slMB-xuck2dajI85Ha-nPXnnaitWpFUmy4sahXMH-cA'
ADMIN_PASS_OBF = "YWRtaW4xMjM="
